import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-full w-full`}
        >
          <header className="flex justify-end px-6 py-4 gap-2">
            <SignedOut>
              <SignInButton mode="modal">
                <button className="px-4 py-2 text-sm font-medium rounded-md bg-white text-black hover:bg-zinc-100 transition-colors cursor-pointer">
                  Sign In
                </button>
              </SignInButton>
              <SignUpButton mode="modal">
                <button className="px-4 py-2 text-sm font-medium rounded-md bg-blue-600 text-white hover:bg-blue-700 transition-colors cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          {children}
          <footer className="mt-auto border-t border-zinc-800 px-6 py-8 text-sm text-zinc-500">
            <div className="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
              <p>© {new Date().getFullYear()} Lifting Diary. All rights reserved.</p>
              <nav className="flex gap-6">
                <a href="https://example.com" className="hover:text-zinc-300 transition-colors">Company Site</a>
                <a href="/privacy" className="hover:text-zinc-300 transition-colors">Privacy Policy</a>
                <a href="/terms" className="hover:text-zinc-300 transition-colors">Terms of Service</a>
                <a href="mailto:support@example.com" className="hover:text-zinc-300 transition-colors">Contact</a>
              </nav>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
